"""Add metadata_json to Item model

Revision ID: 29828fb7031e
Revises: 4e1a1a4bfe98
Create Date: 2025-05-10 22:54:21.602314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29828fb7031e'
down_revision = '4e1a1a4bfe98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metadata_json', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('metadata_json')

    # ### end Alembic commands ###
