"""Refactor Item to Weapon, update PictoLumina and build relationships

Revision ID: 2bedc6a8f16a
Revises: 
Create Date: 2025-05-11 21:12:54.418163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bedc6a8f16a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_characters_coe33',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_stats_json', sa.JSON(), nullable=True),
    sa.Column('unique_mechanic_description', sa.Text(), nullable=True),
    sa.Column('icon_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    with op.batch_alter_table('game_characters_coe33', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_characters_coe33_name'), ['name'], unique=True)

    op.create_table('pictoluminas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('lp_cost', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('effect_details_json', sa.JSON(), nullable=True),
    sa.Column('picto_variants_json', sa.JSON(), nullable=True),
    sa.Column('tags_json', sa.JSON(), nullable=True),
    sa.Column('spoiler_info_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pictoluminas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pictoluminas_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pictoluminas_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('profile_info', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('skills_coe33',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('character_name', sa.String(length=100), nullable=True),
    sa.Column('ap_cost', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('effects_json', sa.JSON(), nullable=True),
    sa.Column('mechanics_json', sa.JSON(), nullable=True),
    sa.Column('tags_json', sa.JSON(), nullable=True),
    sa.Column('is_gradient_attack', sa.Boolean(), nullable=False),
    sa.Column('spoiler_info_json', sa.JSON(), nullable=True),
    sa.Column('icon_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['character_name'], ['game_characters_coe33.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skills_coe33', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skills_coe33_character_name'), ['character_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_skills_coe33_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_skills_coe33_name'), ['name'], unique=True)

    op.create_table('weapons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('weapon_type', sa.String(length=50), nullable=False),
    sa.Column('element', sa.String(length=50), nullable=True),
    sa.Column('power_by_level_json', sa.JSON(), nullable=True),
    sa.Column('attribute_scaling_tiers_json', sa.JSON(), nullable=True),
    sa.Column('passive_effects_by_level_json', sa.JSON(), nullable=True),
    sa.Column('acquisition_info', sa.Text(), nullable=True),
    sa.Column('icon_url', sa.String(length=255), nullable=True),
    sa.Column('character_restriction_name', sa.String(length=100), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('spoiler_info_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['character_restriction_name'], ['game_characters_coe33.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weapons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weapons_character_restriction_name'), ['character_restriction_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_weapons_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weapons_name'), ['name'], unique=True)

    op.create_table('user_builds_coe33',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('character_name', sa.String(length=100), nullable=False),
    sa.Column('build_title', sa.String(length=200), nullable=False),
    sa.Column('build_description', sa.Text(), nullable=True),
    sa.Column('equipped_weapon_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('rating_score', sa.Float(), nullable=True),
    sa.Column('total_views', sa.Integer(), nullable=True),
    sa.Column('attribute_points_allocated_json', sa.JSON(), nullable=True),
    sa.Column('character_level_for_build', sa.Integer(), nullable=True),
    sa.Column('weapon_level_for_build', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_name'], ['game_characters_coe33.name'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['equipped_weapon_id'], ['weapons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_builds_coe33', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_builds_coe33_id'), ['id'], unique=False)

    op.create_table('build_assigned_pictoluminas',
    sa.Column('user_build_id', sa.Integer(), nullable=False),
    sa.Column('pictolumina_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pictolumina_id'], ['pictoluminas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_build_id'], ['user_builds_coe33.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_build_id', 'pictolumina_id')
    )
    op.create_table('build_equipped_pictos',
    sa.Column('user_build_id', sa.Integer(), nullable=False),
    sa.Column('pictolumina_id', sa.Integer(), nullable=False),
    sa.Column('picto_variant_key', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['pictolumina_id'], ['pictoluminas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_build_id'], ['user_builds_coe33.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_build_id', 'pictolumina_id', 'picto_variant_key')
    )
    op.create_table('build_skills_association',
    sa.Column('user_build_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills_coe33.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_build_id'], ['user_builds_coe33.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_build_id', 'skill_id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('build_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['build_id'], ['user_builds_coe33.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_table('build_skills_association')
    op.drop_table('build_equipped_pictos')
    op.drop_table('build_assigned_pictoluminas')
    with op.batch_alter_table('user_builds_coe33', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_builds_coe33_id'))

    op.drop_table('user_builds_coe33')
    with op.batch_alter_table('weapons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weapons_name'))
        batch_op.drop_index(batch_op.f('ix_weapons_id'))
        batch_op.drop_index(batch_op.f('ix_weapons_character_restriction_name'))

    op.drop_table('weapons')
    with op.batch_alter_table('skills_coe33', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skills_coe33_name'))
        batch_op.drop_index(batch_op.f('ix_skills_coe33_id'))
        batch_op.drop_index(batch_op.f('ix_skills_coe33_character_name'))

    op.drop_table('skills_coe33')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('pictoluminas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pictoluminas_name'))
        batch_op.drop_index(batch_op.f('ix_pictoluminas_id'))

    op.drop_table('pictoluminas')
    with op.batch_alter_table('game_characters_coe33', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_characters_coe33_name'))

    op.drop_table('game_characters_coe33')
    # ### end Alembic commands ###
