"""Update unique constraint to use level instead of tier in PictoCOE33 model

Revision ID: 3fe0d053c4d8
Revises: aee9ad3bdf0c
Create Date: 2025-05-11 17:10:09.316371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fe0d053c4d8'
down_revision = 'aee9ad3bdf0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('luminas_coe33', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=True))
        batch_op.drop_column('icon_url')

    with op.batch_alter_table('pictos_coe33', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('tags_json', sa.JSON(), nullable=True))
        batch_op.alter_column('associated_lumina_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index('ix_pictos_coe33_name')
        batch_op.create_index(batch_op.f('ix_pictos_coe33_name'), ['name'], unique=False)
        batch_op.create_unique_constraint('_picto_name_level_uc', ['name', 'level'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pictos_coe33', schema=None) as batch_op:
        batch_op.drop_constraint('_picto_name_level_uc', type_='unique')
        batch_op.drop_index(batch_op.f('ix_pictos_coe33_name'))
        batch_op.create_index('ix_pictos_coe33_name', ['name'], unique=1)
        batch_op.alter_column('associated_lumina_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('tags_json')
        batch_op.drop_column('level')

    with op.batch_alter_table('luminas_coe33', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('type')
        batch_op.drop_column('tags_json')

    # ### end Alembic commands ###
