"""Add detailed weapon progression fields to Item model

Revision ID: 4c6ace8b8695
Revises: c4b326dbc619
Create Date: 2025-05-10 17:32:01.624750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c6ace8b8695'
down_revision = 'c4b326dbc619'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('element', sa.String(length=50), nullable=True),
    sa.Column('power_by_level_json', sa.JSON(), nullable=True),
    sa.Column('attribute_scaling_tiers_json', sa.JSON(), nullable=True),
    sa.Column('passive_effects_by_level_json', sa.JSON(), nullable=True),
    sa.Column('acquisition_info', sa.Text(), nullable=True),
    sa.Column('icon_url', sa.String(length=255), nullable=True),
    sa.Column('primary_character_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_items_primary_character_name'), ['primary_character_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_primary_character_name'))
        batch_op.drop_index(batch_op.f('ix_items_name'))
        batch_op.drop_index(batch_op.f('ix_items_id'))

    op.drop_table('items')
    # ### end Alembic commands ###
