"""Add is_gradient_attack and other fields to Skill model

Revision ID: 4e1a1a4bfe98
Revises: 4c6ace8b8695
Create Date: 2025-05-10 22:24:44.715847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e1a1a4bfe98'
down_revision = '4c6ace8b8695'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skills_coe33', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('mechanics_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('is_gradient_attack', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_skills_coe33_character_name'), ['character_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skills_coe33', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skills_coe33_character_name'))
        batch_op.drop_column('is_gradient_attack')
        batch_op.drop_column('mechanics_json')
        batch_op.drop_column('character_name')

    # ### end Alembic commands ###
