"""Initial migration

Revision ID: 560379f3857d
Revises: 
Create Date: 2025-05-10 15:09:30.327118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '560379f3857d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_characters_coe33',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_stats_json', sa.JSON(), nullable=True),
    sa.Column('unique_mechanic_description', sa.Text(), nullable=True),
    sa.Column('icon_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_characters_coe33', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_characters_coe33_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_characters_coe33_name'), ['name'], unique=True)

    op.create_table('luminas_coe33',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('lumina_point_cost', sa.Integer(), nullable=False),
    sa.Column('effect_details_json', sa.JSON(), nullable=True),
    sa.Column('icon_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('luminas_coe33', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_luminas_coe33_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_luminas_coe33_name'), ['name'], unique=True)

    op.create_table('skills_coe33',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ap_cost', sa.Integer(), nullable=True),
    sa.Column('effects_json', sa.JSON(), nullable=True),
    sa.Column('icon_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skills_coe33', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skills_coe33_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_skills_coe33_name'), ['name'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('profile_info', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('pictos_coe33',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('stat_bonuses_json', sa.JSON(), nullable=True),
    sa.Column('associated_lumina_id', sa.Integer(), nullable=True),
    sa.Column('how_to_acquire', sa.Text(), nullable=True),
    sa.Column('icon_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['associated_lumina_id'], ['luminas_coe33.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('associated_lumina_id')
    )
    with op.batch_alter_table('pictos_coe33', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pictos_coe33_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pictos_coe33_name'), ['name'], unique=True)

    op.create_table('user_builds_coe33',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('build_title', sa.String(length=200), nullable=False),
    sa.Column('build_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('rating_score', sa.Float(), nullable=True),
    sa.Column('total_views', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['game_characters_coe33.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_builds_coe33', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_builds_coe33_id'), ['id'], unique=False)

    op.create_table('build_luminas_association_coe33',
    sa.Column('user_build_id', sa.Integer(), nullable=False),
    sa.Column('lumina_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lumina_id'], ['luminas_coe33.id'], ),
    sa.ForeignKeyConstraint(['user_build_id'], ['user_builds_coe33.id'], ),
    sa.PrimaryKeyConstraint('user_build_id', 'lumina_id')
    )
    op.create_table('build_pictos_association_coe33',
    sa.Column('user_build_id', sa.Integer(), nullable=False),
    sa.Column('picto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['picto_id'], ['pictos_coe33.id'], ),
    sa.ForeignKeyConstraint(['user_build_id'], ['user_builds_coe33.id'], ),
    sa.PrimaryKeyConstraint('user_build_id', 'picto_id')
    )
    op.create_table('build_skills_association_coe33',
    sa.Column('user_build_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills_coe33.id'], ),
    sa.ForeignKeyConstraint(['user_build_id'], ['user_builds_coe33.id'], ),
    sa.PrimaryKeyConstraint('user_build_id', 'skill_id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('build_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['build_id'], ['user_builds_coe33.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_table('build_skills_association_coe33')
    op.drop_table('build_pictos_association_coe33')
    op.drop_table('build_luminas_association_coe33')
    with op.batch_alter_table('user_builds_coe33', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_builds_coe33_id'))

    op.drop_table('user_builds_coe33')
    with op.batch_alter_table('pictos_coe33', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pictos_coe33_name'))
        batch_op.drop_index(batch_op.f('ix_pictos_coe33_id'))

    op.drop_table('pictos_coe33')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('skills_coe33', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skills_coe33_name'))
        batch_op.drop_index(batch_op.f('ix_skills_coe33_id'))

    op.drop_table('skills_coe33')
    with op.batch_alter_table('luminas_coe33', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_luminas_coe33_name'))
        batch_op.drop_index(batch_op.f('ix_luminas_coe33_id'))

    op.drop_table('luminas_coe33')
    with op.batch_alter_table('game_characters_coe33', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_characters_coe33_name'))
        batch_op.drop_index(batch_op.f('ix_game_characters_coe33_id'))

    op.drop_table('game_characters_coe33')
    # ### end Alembic commands ###
