"""Add tags_json to SkillCOE33 model

Revision ID: 665cc609cb4e
Revises: 29828fb7031e
Create Date: 2025-05-11 15:22:43.269298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '665cc609cb4e'
down_revision = '29828fb7031e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skills_coe33', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags_json', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skills_coe33', schema=None) as batch_op:
        batch_op.drop_column('tags_json')

    # ### end Alembic commands ###
