"""Drop Item table and update Weapon table

Revision ID: aee9ad3bdf0c
Revises: 665cc609cb4e
Create Date: 2025-05-11 15:35:56.346536

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'aee9ad3bdf0c'
down_revision = '665cc609cb4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weapons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('weapons_type', sa.String(length=50), nullable=False),
    sa.Column('element', sa.String(length=50), nullable=True),
    sa.Column('spoiler_info_json', sa.JSON(), nullable=True),
    sa.Column('power_by_level_json', sa.JSON(), nullable=True),
    sa.Column('attribute_scaling_tiers_json', sa.JSON(), nullable=True),
    sa.Column('passive_effects_by_level_json', sa.JSON(), nullable=True),
    sa.Column('acquisition_info', sa.Text(), nullable=True),
    sa.Column('icon_url', sa.String(length=255), nullable=True),
    sa.Column('primary_character_name', sa.String(length=100), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weapons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weapons_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weapons_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_weapons_primary_character_name'), ['primary_character_name'], unique=False)

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index('ix_items_id')
        batch_op.drop_index('ix_items_name')
        batch_op.drop_index('ix_items_primary_character_name')

    op.drop_table('items')
    with op.batch_alter_table('game_characters_coe33', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spoiler_info_json', sa.JSON(), nullable=True))

    with op.batch_alter_table('luminas_coe33', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spoiler_info_json', sa.JSON(), nullable=True))

    with op.batch_alter_table('pictos_coe33', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spoiler_info_json', sa.JSON(), nullable=True))

    with op.batch_alter_table('skills_coe33', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spoiler_info_json', sa.JSON(), nullable=True))

    with op.batch_alter_table('user_builds_coe33', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spoiler_info_json', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_builds_coe33', schema=None) as batch_op:
        batch_op.drop_column('spoiler_info_json')

    with op.batch_alter_table('skills_coe33', schema=None) as batch_op:
        batch_op.drop_column('spoiler_info_json')

    with op.batch_alter_table('pictos_coe33', schema=None) as batch_op:
        batch_op.drop_column('spoiler_info_json')

    with op.batch_alter_table('luminas_coe33', schema=None) as batch_op:
        batch_op.drop_column('spoiler_info_json')

    with op.batch_alter_table('game_characters_coe33', schema=None) as batch_op:
        batch_op.drop_column('spoiler_info_json')

    op.create_table('items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('item_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('element', sa.VARCHAR(length=50), nullable=True),
    sa.Column('power_by_level_json', sqlite.JSON(), nullable=True),
    sa.Column('attribute_scaling_tiers_json', sqlite.JSON(), nullable=True),
    sa.Column('passive_effects_by_level_json', sqlite.JSON(), nullable=True),
    sa.Column('acquisition_info', sa.TEXT(), nullable=True),
    sa.Column('icon_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('primary_character_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('metadata_json', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index('ix_items_primary_character_name', ['primary_character_name'], unique=False)
        batch_op.create_index('ix_items_name', ['name'], unique=1)
        batch_op.create_index('ix_items_id', ['id'], unique=False)

    with op.batch_alter_table('weapons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weapons_primary_character_name'))
        batch_op.drop_index(batch_op.f('ix_weapons_name'))
        batch_op.drop_index(batch_op.f('ix_weapons_id'))

    op.drop_table('weapons')
    # ### end Alembic commands ###
